# 应用服务 WEB 访问端口
server:
  port: 8079

spring:
  datasource:
    # Druid的其他属性配置 springboot3整合情况下,数据库连接信息必须在Druid属性下!
    #    url: jdbc:mysql://localhost:3306/elm
    url: jdbc:mysql://localhost:3306/tijian
    username: root
    password: MySQLZcw7g2ua
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    #smtp服务主机  qq邮箱则为smtp.qq.com
    host: smtp.qq.com
    port: 587
    #服务协议
    protocol: smtp
    # 编码集
    default-encoding: UTF-8
    #发送邮件的账户
    username: 1914575145@qq.com  #这里没有办法自己给自己发
    #授权码
    password: fhtaalwgmxrrbahj
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

#jwt配置
jwt:
  token:
    tokenExpiration: 15 #有效时间,单位分钟
    tokenSignKey: 123456  #当前程序签名秘钥 自定义

